# Generated by Django 6.0.1 on 2026-02-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_lessonprogress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='https://www.youtube.com/watch?v=UVkpH6KWFnk&t=4s', null=True),
        ),
    ]
